dist: trusty
sudo: required
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build and publish
  - deploy
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: node_js
       node_js:
        - "10"
      install: skip
      script: yarn test
